version: '2.1'
orbs:
  slack: circleci/slack@4.0
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: newman run just_200.postman_collection.json -e production.postman_environment.json --reporters cli --bail newman
      - slack/notify:
          channel: 'C01C5C7GY06'
          template: basic_fail_1
          event: always
          mentions: '@huangxiaoqian'
workflows:
  test-and-notification:
    jobs:
      - test
        
          

