version: '2.1'
orbs:
  slack: circleci/slack@4.0
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./just_200.postman_collection.json
          environment: ./production.postman_environment.json
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: 'C01C5C7GY06'
          template: basic_fail_1
          event: always
          mentions: '@huangxiaoqian'
workflows:
  test-and-notification:
    triggers:
      - schedule:
          cron: '5 * * * *'
          filters:
            branches:
              only:
                - circleci-project-setup

    jobs:
      - newman-collection-run
      - notify
        
          

