version: '2.1'
orbs:
  slack: circleci/slack@4.0
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: 'C01C5C7GY06'
          custom: |
            {
	"blocks": [
		{
			"type": "section",
			"text": {
				"type": "plain_text",
				"text": "This is a plain text section block.",
				"emoji": true
			}
		},
		{
			"type": "section",
			"text": {
				"type": "plain_text",
				"text": "This is a plain text section block.",
				"emoji": true
			}
		}
	]
}
          event: always
workflows:
  send-notification:
    jobs:
      - notify
        
          

