version: 2.1
orbs:
  slack: circleci/slack@4.0
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - run: 
          name: "install curl"
          command: apt-get install curl
      - checkout
      - newman/newman-run:
          collection: ./just_200.postman_collection.json
          environment: ./production.postman_environment.json
      - slack/notify:
          channel: 'C01C5C7GY06'
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
          mentions: '@U0148JK5ZHQ'
#   notify:
#     docker:
#       - image: 'cimg/base:stable'
#     steps:
#       - slack/notify:
#           channel: 'C01C5C7GY06'
#           custom: |
#             {
#               "blocks": [
#                 {
#                   "type": "section",
#                   "fields": [
#                     {
#                       "type": "plain_text",
#                       "text": "*This is a text notification*",
#                       "emoji": true
#                     }
#                   ]
#                 }
#               ]
#             }
#           event: always
#           mentions: '@U0148JK5ZHQ'
        
          
workflows:
  test-and-notification:
    triggers:
      - schedule:
#           cron: "0,9,19,29,39,49,59 * * * *"
          cron: "* * * * *"
          filters:
            branches:
              only:
                - circleci-project-setup

    jobs:
      - newman-collection-run
#       - notify
        

